[package]
authors = ["konstin <konstin@mailbox.org>"]
name = "pyo3-pack"
version = "0.7.0-beta.11"
description = "Build and publish crates with pyo3, rust-cpython and cffi bindings as well as rust binaries as python packages"
exclude = ["test-crates/**/*", "sysconfig/*", "test-data/*", "ci/*", "tests/*"]
readme = "Readme.md"
repository = "https://github.com/pyo3/pyo3-pack"
license = "MIT OR Apache-2.0"
keywords = ["python", "cffi", "packaging", "pypi", "pyo3"]
categories = ["api-bindings", "development-tools::ffi", "command-line-utilities"]
edition = "2018"

[package.metadata.pyo3-pack]
classifier = [
    "Software Development :: Build Tools",
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy"
]
requires-dist = ["toml~=0.10.0"]

[badges]
travis-ci = { repository = "PyO3/pyo3-pack" }
appveyor = { repository = "konstin/pyo3" }

[[bin]]
name = "pyo3-pack"

[lib]
name = "pyo3_pack"

[dependencies]
base64 = "0.10.1"
cargo_metadata = "0.8.1"
digest = { version = "0.8.1", features = ["std"] }
failure = "0.1.5"
keyring = { version = "0.7.0", optional = true }
rpassword = { version = "4.0.1", optional = true }
serde_json = "1.0.40"
sha2 = "0.8.0"
structopt = "0.2.18"
target_info = "0.1.0"
toml = "0.5.1"
zip = "0.5.2"
serde = { version = "1.0.98", features = ["derive"] }
human-panic = { version = "1.0.1", optional = true }
regex = "1.2.1"
tempfile = "3.1.0"
goblin = "0.0.24"
pretty_env_logger = { version = "0.3.0", optional = true }
platforms = "0.2.0"
shlex = "0.1.1"
cbindgen = { version = "0.9.0", default-features = false }
walkdir = "2.2.8"
flate2 = "1.0.9"
tar = "0.4.26"
curl = { version = "0.4.22", optional = true, default-features = false, features = ["static-curl", "ssl", "static-ssl"] }
curl-sys = { version = "0.4.20", optional = true, default-features = false }
log = "0.4.8"

[dev-dependencies]
indoc = "0.3.3"

[features]
default = ["auditwheel", "pretty-env-logger", "upload"]
auditwheel = []
upload = ["curl", "curl-sys", "rpassword"]
password-storage = ["upload", "keyring"]
pretty-env-logger = ["pretty_env_logger"]
# Internal feature to run test with stable rust
skip-nightly-tests = []
# Internal feature to speed up the tests significantly
faster-tests = []

[patch.crates-io]
curl = { git = "https://github.com/alexcrichton/curl-rust", rev = "20162df06dd9becc951926988d8a5da649850b0b" }
curl-sys = { git = "https://github.com/alexcrichton/curl-rust", rev = "20162df06dd9becc951926988d8a5da649850b0b" }
